name: Create Kafka Topic and Partitions

on:
  workflow_dispatch:
    inputs:
      topic_name:
        description: 'Topic Name'
        required: true
      partitions:
        description: 'Number of Partitions'
        required: true

jobs:
  create_topic:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create Kafka Topic and Partitions
        run: |
          python main_module.py "${{ github.event.inputs.topic_name }}" "${{ github.event.inputs.partitions }}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
