name: Run Python Script

on:
  push:
    branches:
      - main  # or the name of your default branch, e.g., "master"

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # or the desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # If you have a 'requirements.txt' file in your repo, uncomment the following line
        # pip install -r requirements.txt

    - name: Run Python script
      run: python hello.py  # Replace 'your_script.py' with the name of your Python file
